name: Notify Discord on Push

on:
  push:
    branches:
      - main

jobs:
  discord:
    runs-on: ubuntu-latest
    steps:
      - name: Send commit info to Discord
        uses: tsickert/discord-webhook-action@v1.2.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          username: ${{ github.actor }}
          avatar-url: https://github.com/${{ github.actor }}.png
          embed-title: "[${{ github.repository }}:${{ github.ref_name }}] New Commit"
          embed-url: ${{ github.event.head_commit.url }}
          embed-description: |
            [`${{ github.event.head_commit.id }}`] ${{ github.event.head_commit.message }} - ${{ github.actor }}
          embed-color: 3447003
