name: Notify Discord on Commit

on:
  push:
    branches:
      - main

jobs:
  discord:
    runs-on: ubuntu-latest
    steps:
      - name: Send commit to Discord
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: |
            **${{ github.actor }}** pushed to **${{ github.repository }}**:
            `${{ github.event.head_commit.message }}`
            <${{ github.event.head_commit.url }}>
