name: Discord Webhook Commit Notifications

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send commit information to Discord
        uses: tsickert/discord-webhook-action@v1.2.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          username: 'GitHub'
          avatar_url: 'https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png' # GitHub logo
          content: |
            **Avatar** comfrog559098
            **[rom:main]** ${{ github.event.commits | size }} new commit{{ github.event.commits | size > 1 && 's' || '' }}: [Repository Link](https://github.com/DashleafStudio/CalloftheVoid)
            ${{ github.sha.substring(0, 7) }} [Commit Link](https://github.com/DashleafStudio/CalloftheVoid/commit/${{ github.sha }}) {{ github.event.head_commit.message }} - comfrog559098
