name: Discord Webhook Commit Notifications

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send commit information to Discord
        uses: actions/github-script@v6
        with:
          script: |
            const webhookUrl = process.env.DISCORD_WEBHOOK_URL;
            
            // Check if there are multiple commits
            const commitsCount = github.event.commits.length;
            const repoName = github.repository.split('/')[1];
            
            let content = `**Avatar** comfrog559098\n`;
            content += `**[${repoName}:main]** ${commitsCount} new commit${commitsCount > 1 ? 's' : ''}: [Repository Link](https://github.com/${github.repository})\n`;
            
            // Iterate through commits and create message for each
            github.event.commits.forEach(commit => {
              const commitId = commit.id.substring(0, 7);
              const commitMessage = commit.message;
              content += `**Commit ID** ${commitId} [Commit Link](https://github.com/${github.repository}/commit/${commitId})\n`;
              content += `${commitMessage} - comfrog559098\n`;
            });

            const response = await fetch(webhookUrl, {
              method: 'POST',
              headers: {
                'Content-Type': 'application/json',
              },
              body: JSON.stringify({ content }),
            });

            if (!response.ok) {
              throw new Error(`Error sending Discord message: ${response.statusText}`);
            }
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
