name: Discord Commit Notifications

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Get commit details
      id: commit_info
      run: |
        echo "::set-output name=commit_message::$(git log -1 --pretty=%B)"
        echo "::set-output name=commit_id::$(git log -1 --pretty=%h)"
        echo "::set-output name=commit_url::$(git log -1 --pretty=%H)"
        echo "::set-output name=commit_author::$(git log -1 --pretty=%an)"
        echo "::set-output name=commit_avatar::$(git log -1 --pretty=%aE)"

    - name: Send commit info to Discord
      uses: tsickert/discord-webhook-action@v1.2.0
      with:
        webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
        username: 'GitHub Actions'
        avatar_url: ${{ steps.commit_info.outputs.commit_avatar }}
        content: |
          **AVATAR:** ${{ steps.commit_info.outputs.commit_author }}
          **[${{ github.repository }}:${{ github.ref }}]** ${{ github.event.commits | size }} new commit(s)
          [LINK TO REPOSITORY](${{
          github.repository_url
          }})
          **${{ steps.commit_info.outputs.commit_id }}**
          [LINK TO COMMIT](https://github.com/${{ github.repository }}/commit/${{ steps.commit_info.outputs.commit_id }})
          ${{ steps.commit_info.outputs.commit_message }}
