curl -H "Content-Type: application/json" \
-X POST \
-d '{"content": "Hello, Discord!"}' \
https://discord.com/api/webhooks/1369408115518341221/dCV6KMxFsunKgO0q--Dply2lxMRiXT7RHaCa_A_Kla2_SObhFNyVCAsxcfLGwW16cI9e
