name: Notify Discord on Commit

on:
  push:
    branches:
      - main

jobs:
  discord:
    runs-on: ubuntu-latest
    steps:
      - name: Send formatted commit message to Discord
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: |
            **[CalloftheVoid:main]** ${{ github.event.commits | size }} new ${{ github.event.commits | size > 1 && 'commits' || 'commit' }}
            [`${{ github.event.head_commit.id.substr(0, 7) }}`](${{ github.event.head_commit.url }}) ${{ github.event.head_commit.message }} - ${{ github.actor }}
