name: Discord Notify

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send webhook to Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
          COMMIT_URL: ${{ github.event.head_commit.url }}
          COMMIT_ID: ${{ github.event.head_commit.id }}
          AUTHOR_NAME: ${{ github.event.head_commit.author.name }}
          REPO_NAME: ${{ github.repository }}
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{
                    "username": "GitHub",
                    "avatar_url": "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png",
                    "embeds": [{
                      "title": "[${REPO_NAME}:main] 1 new commit",
                      "url": "${COMMIT_URL}",
                      "description": "[`${COMMIT_ID:0:7}`] ${COMMIT_MESSAGE} - ${AUTHOR_NAME}",
                      "color": 7506394
                    }]
                  }' \
               $DISCORD_WEBHOOK
