curl -H "Content-Type: application/json" \
     -X POST \
     -d '{
          "username": "GitHub",
          "avatar_url": "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png",
          "embeds": [{
            "title": "[${REPO_NAME}:main] 1 new commit",
            "url": "${COMMIT_URL}",
            "description": "[`${COMMIT_ID:0:7}`] ${COMMIT_MESSAGE} - ${AUTHOR_NAME}",
            "color": 7506394
          }]
        }' \
     $DISCORD_WEBHOOK
